#!/bin/sh

API_URL=https://api.hashland.cc

. $HOME/.hashland

# generate a /etc/ethers compatible file which can be used for dhcp servers to do static assignments based on mac address
gen_ethers()
{
	get_miners | jq -r '.data.miners[] | select(.mac != "") | select(.mac != null) | .mac + " " + .ip'
}

get()
{
	ROUTE=$1
	PARAMS=$2
	curl -s -H "Authorization: Bearer $API_KEY" ${API_URL}/$ROUTE?$PARAMS
}

get_miners()
{
	get "miners" $1 | jq .data.miners[] 
}

if [ -z $1 ]; then
	echo usage:
        echo $ hl gen_ethers\|get_miners [param=value]
	echo
	echo examples:
	echo
	echo Get miners by name:
        echo $ hl get_miners name=XXX
	echo
	exit 1
fi
	
$1 $2

